


CREATE VIEW latest_project_with_update_date AS
 SELECT a.id,
    a.project_id,
    a.project_name,
    a.start_date,
    a.short_desc,
    a.phase,
    a.category,
    a.subcat,
    a.rag,
    a.[update],
    a.oddlead,
    a.oddlead_email,
    a.servicelead,
    a.servicelead_email,
    a.priority_main,
    a.funded,
    a.confidence,
    a.priorities,
    a.benefits,
    a.criticality,
    a.budget,
    a.spent,
    a.documents,
    a."timestamp",
    a.pgroup,
    a.link,
    a.toupdate,
    a.rels,
    a.team,
    a.onhold,
    a.expend,
    a.hardend,
    a.actstart,
    a.dependencies,
    a.project_size,
    a.oddlead_role,
    a.budgettype,
    a.direct,
    a.expendp,
    a.p_comp,
    a.max_time,
    a.min_time,
    a.g6team,
    a.new_flag,
    b.latest_update
   FROM (latest_projects a
     LEFT JOIN updates_latest_date b ON (((a.project_id) = (b.project_id))));