

CREATE VIEW latest_projects_int3 AS
 SELECT a.id,
    a.project_id,
    a.project_name,
    a.start_date,
    a.short_desc,
    a.phase,
    a.category,
    a.subcat,
    a.rag,
    a.[update],
    a.oddlead,
    a.oddlead_email,
    a.servicelead,
    a.servicelead_email,
    a.priority_main,
    a.funded,
    a.confidence,
    a.priorities,
    a.benefits,
    a.criticality,
    a.budget,
    a.spent,
    a.documents,
    a."timestamp",
    a.pgroup,
    a.link,
    a.toupdate,
    a.rels,
    a.team,
    a.onhold,
    a.expend,
    a.hardend,
    a.actstart,
    a.dependencies,
    a.project_size,
    a.oddlead_role,
    a.budgettype,
    a.direct,
    a.expendp,
    a.p_comp,
    a.max_time,
    a.min_time,
    b.g6team
   FROM (latest_projects_int2 a
     LEFT JOIN odd_people b ON (((a.oddlead_email) = (b.email))));