echo Initialising access groups...
curl -s $apiUrl/AccessGroups/init -H "APIKey: $apiKey"
echo Creating user...
curl -s $apiUrl/Users/create -X POST -d userName=$apiUser -d password=$apiUserPassword -d accessgroup=$apiUserAccessGroup -H "APIKey: $apiKey" 
source getToken.sh
echo Creating a new portfolio...
curl -s $apiUrl/NewPortfolio -X POST --data "{ \"viewkey\": \"$apiPortfolioKey\", \"abbr\": \"$apiPortfolioKey\", \"name\": \"$apiPortfolioName\", \"description\": \"$apiPortfolioName\" }" -H "APIKey: $apiKey" -H "Authorization: Bearer $access_token" -H "Content-Type: application/json" 
echo Giving user permission on the portfolio...
curl -s $apiUrl/Portfolios/$apiPortfolioKey/permission -X POST --data "{ \"userName\": \"$apiUser\", \"permission\": \"$apiUserPortfolioRole\" }" -H "APIKey: $apiKey" -H "Authorization: Bearer $access_token" -H "Content-Type: application/json"
