echo Initialising access groups...
curl $apiUrl/AccessGroups/init -H "APIKey: $apiKey"
echo Creating user...
curl $apiUrl/Users/create -X POST -d userName=$apiUser -d password=$apiUserPassword -d accessgroup=$apiUserAccessGroup -H "APIKey: $apiKey" 
source getToken.sh
echo Creating a new portfolio...
curl $apiUrl/NewPortfolio -X POST --data "{ \"viewkey\": \"$apiPortfolioKey\", \"abbr\": \"work\", \"name\": \"Work\", \"description\": \"Work\" }" -H "APIKey: $apiKey" -H "Authorization: Bearer $access_token" -H "Content-Type: application/json" 
echo Giving user permission on the portfolio...
curl $apiUrl/Portfolios/$apiPortfolioKey/permission -X POST --data "{ \"userName\": \"$apiUser\", \"permission\": \"$apiUserPortfolioRole\" }" -H "APIKey: $apiKey" -H "Authorization: Bearer $access_token" -H "Content-Type: application/json"
