// <auto-generated />
namespace FSAPortfolio.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Portfolio3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Portfolio3));
        
        string IMigrationMetadata.Id
        {
            get { return "202010021202072_Portfolio3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
