// <auto-generated />
namespace FSAPortfolio.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _04_AccessGroupViewKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04_AccessGroupViewKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202011181132051_04_AccessGroupViewKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
