// <auto-generated />
namespace FSAPortfolio.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _03_Archive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03_Archive));
        
        string IMigrationMetadata.Id
        {
            get { return "202101061329228_03_Archive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
