CREATE TABLE [dbo].[projects] (
    [id]                INT            IDENTITY (1, 1) NOT NULL,
    [project_id]        VARCHAR (10)   NULL,
    [project_name]      VARCHAR (250)  NULL,
    [start_date]        VARCHAR (50)   NULL,
    [short_desc]        VARCHAR (1000) NULL,
    [phase]             VARCHAR (50)   NULL,
    [category]          VARCHAR (50)   NULL,
    [subcat]            VARCHAR (150)  NULL,
    [rag]               VARCHAR (50)   NULL,
    [update]            NVARCHAR (MAX) NULL,
    [oddlead]           VARCHAR (150)  NULL,
    [oddlead_email]     VARCHAR (150)  NULL,
    [servicelead]       VARCHAR (150)  NULL,
    [servicelead_email] VARCHAR (150)  NULL,
    [priority_main]     VARCHAR (3)    NULL,
    [funded]            VARCHAR (3)    NULL,
    [confidence]        VARCHAR (3)    NULL,
    [priorities]        VARCHAR (3)    NULL,
    [benefits]          VARCHAR (3)    NULL,
    [criticality]       VARCHAR (3)    NULL,
    [budget]            VARCHAR (15)   NULL,
    [spent]             VARCHAR (15)   NULL,
    [documents]         VARCHAR (2000) NULL,
    [timestamp]         DATETIME       NOT NULL DEFAULT (getdate()),
    [pgroup]            VARCHAR (20)   NULL,
    [link]              VARCHAR (1000) NULL,
    [toupdate]          CHAR (1)       NULL,
    [rels]              VARCHAR (500)  NULL,
    [team]              VARCHAR (500)  NULL,
    [onhold]            VARCHAR (10)   NULL,
    [expend]            VARCHAR (50)   NULL,
    [hardend]           VARCHAR (50)   NULL,
    [actstart]          VARCHAR (50)   NULL,
    [dependencies]      VARCHAR (500)  NULL,
    [project_size]      VARCHAR (5)    NULL,
    [oddlead_role]      VARCHAR (5)    NULL,
    [budgettype]        VARCHAR (15)   NULL,
    [direct]            VARCHAR (150)  NULL,
    [expendp]           VARCHAR (12)   NULL,
    [p_comp]            REAL           NULL
);

